# Generated by Django 2.2.7 on 2020-07-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_do_cliente', models.CharField(max_length=100)),
                ('Nascimento', models.DateField()),
                ('Tipo_de_Teste_realizado', models.CharField(choices=[('RT-PCR', 'RT-PCR'), ('Sorologia', 'Sorologia'), ('TAntigenos', 'Teste Rápido - Antígenos'), ('TAnticorpos', 'Teste Rápido - Anticorpos')], max_length=50)),
                ('Resultado_do_Teste', models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=50)),
            ],
        ),
    ]
